// app/layout.tsx
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Outfit } from "next/font/google";
import Provider from "./provider";
import { Toaster} from "../components/ui/sonner";
import DashboardHeader from "../app/dashboard/_components/DashboardHeader"; // Import your header component

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={outfit.className}>
          <Provider>
            {/* Dashboard Header */}
            <div className="w-full">
              <DashboardHeader />
              {/* Content area where the children will go */}
        
            <div className="mt-5 p-10">
                {children}
            </div>
            
            </div>
          </Provider>



          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
